DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employees;

CREATE TABLE departments (
     id INTEGER AUTO_INCREMENT PRIMARY KEY,
     department_name VARCHAR(30) NOT NULL
     );

CREATE TABLE roles (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
job_title VARCHAR(30) NOT NULL,
department VARCHAR(30) NOT NULL,
salary VARCHAR(30) NOT NULL
);

CREATE TABLE employees (
     id INTEGER AUTO_INCREMENT PRIMARY KEY,
     first_name VARCHAR(30) NOT NULL,
     last_name VARCHAR(30) NOT NULL,
     department VARCHAR(30) NOT NULL,
     salary VARCHAR(30) NOT NULL,
     managers VARCHAR(30) NOT NULL
);